
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action FileAction;
	
	private global::Gtk.Action ExitAction;
	
	private global::Gtk.Action EditAction;
	
	private global::Gtk.Action CopyAction;
	
	private global::Gtk.Action PasteAction;
	
	private global::Gtk.Action HelpAction;
	
	private global::Gtk.Action AboutAction;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.MenuBar menubar1;
	
	private global::Gtk.Label output;
	
	private global::Gtk.VBox vbox3;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.Frame frame1;
	
	private global::Gtk.Alignment GtkAlignment;
	
	private global::Gtk.Label label1;
	
	private global::Gtk.HButtonBox hbuttonbox2;
	
	private global::Gtk.Button backspace;
	
	private global::Gtk.Button clearField;
	
	private global::Gtk.Button C;
	
	private global::Gtk.VBox vbox4;
	
	private global::Gtk.HButtonBox hbuttonbox3;
	
	private global::Gtk.Button memClear;
	
	private global::Gtk.Button butt7;
	
	private global::Gtk.Button butt8;
	
	private global::Gtk.Button button11;
	
	private global::Gtk.Button button12;
	
	private global::Gtk.Button button38;
	
	private global::Gtk.HButtonBox hbuttonbox4;
	
	private global::Gtk.Button memRead;
	
	private global::Gtk.Button button14;
	
	private global::Gtk.Button button15;
	
	private global::Gtk.Button button16;
	
	private global::Gtk.Button button17;
	
	private global::Gtk.Button button40;
	
	private global::Gtk.HButtonBox hbuttonbox5;
	
	private global::Gtk.Button memSet;
	
	private global::Gtk.Button button19;
	
	private global::Gtk.Button button20;
	
	private global::Gtk.Button button21;
	
	private global::Gtk.Button button22;
	
	private global::Gtk.Button button41;
	
	private global::Gtk.HButtonBox hbuttonbox6;
	
	private global::Gtk.Button memAdd;
	
	private global::Gtk.Button button24;
	
	private global::Gtk.Button button25;
	
	private global::Gtk.Button button26;
	
	private global::Gtk.Button button27;
	
	private global::Gtk.Button button42;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.ExitAction = new global::Gtk.Action ("ExitAction", global::Mono.Unix.Catalog.GetString ("Exit"), null, null);
		this.ExitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Exit");
		w1.Add (this.ExitAction, null);
		this.EditAction = new global::Gtk.Action ("EditAction", global::Mono.Unix.Catalog.GetString ("Edit"), null, null);
		this.EditAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Edit");
		w1.Add (this.EditAction, null);
		this.CopyAction = new global::Gtk.Action ("CopyAction", global::Mono.Unix.Catalog.GetString ("Copy"), null, null);
		this.CopyAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Copy");
		w1.Add (this.CopyAction, null);
		this.PasteAction = new global::Gtk.Action ("PasteAction", global::Mono.Unix.Catalog.GetString ("Paste"), null, null);
		this.PasteAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Paste");
		w1.Add (this.PasteAction, null);
		this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
		this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
		w1.Add (this.HelpAction, null);
		this.AboutAction = new global::Gtk.Action ("AboutAction", global::Mono.Unix.Catalog.GetString ("About"), null, null);
		this.AboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("About");
		w1.Add (this.AboutAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Calculator");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='ExitAction' action='ExitAction'/></menu><menu name='EditAction' action='EditAction'><menuitem name='CopyAction' action='CopyAction'/><menuitem name='PasteAction' action='PasteAction'/></menu><menu name='HelpAction' action='HelpAction'><menuitem name='AboutAction' action='AboutAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.output = new global::Gtk.Label ();
		this.output.Name = "output";
		this.output.Ypad = 2;
		this.output.Xalign = 1F;
		this.output.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.output.Justify = ((global::Gtk.Justification)(1));
		this.vbox1.Add (this.output);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.output]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.frame1 = new global::Gtk.Frame ();
		this.frame1.Name = "frame1";
		this.frame1.ShadowType = ((global::Gtk.ShadowType)(4));
		// Container child frame1.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.Xpad = 31;
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
		this.label1.Justify = ((global::Gtk.Justification)(2));
		this.GtkAlignment.Add (this.label1);
		this.frame1.Add (this.GtkAlignment);
		this.hbox1.Add (this.frame1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.frame1]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.hbuttonbox2 = new global::Gtk.HButtonBox ();
		this.hbuttonbox2.Name = "hbuttonbox2";
		this.hbuttonbox2.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
		// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
		this.backspace = new global::Gtk.Button ();
		this.backspace.CanFocus = true;
		this.backspace.Name = "backspace";
		this.backspace.UseUnderline = true;
		this.backspace.Label = global::Mono.Unix.Catalog.GetString ("Backspace");
		this.hbuttonbox2.Add (this.backspace);
		global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.backspace]));
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
		this.clearField = new global::Gtk.Button ();
		this.clearField.CanFocus = true;
		this.clearField.Name = "clearField";
		this.clearField.UseUnderline = true;
		this.clearField.Label = global::Mono.Unix.Catalog.GetString ("CE");
		this.hbuttonbox2.Add (this.clearField);
		global::Gtk.ButtonBox.ButtonBoxChild w8 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.clearField]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
		this.C = new global::Gtk.Button ();
		this.C.CanFocus = true;
		this.C.Name = "C";
		this.C.UseUnderline = true;
		this.C.Label = global::Mono.Unix.Catalog.GetString ("C");
		this.hbuttonbox2.Add (this.C);
		global::Gtk.ButtonBox.ButtonBoxChild w9 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.C]));
		w9.Position = 2;
		w9.Expand = false;
		w9.Fill = false;
		this.hbox1.Add (this.hbuttonbox2);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.hbuttonbox2]));
		w10.Position = 1;
		this.vbox3.Add (this.hbox1);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox1]));
		w11.Position = 0;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbuttonbox3 = new global::Gtk.HButtonBox ();
		this.hbuttonbox3.Name = "hbuttonbox3";
		this.hbuttonbox3.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
		// Container child hbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
		this.memClear = new global::Gtk.Button ();
		this.memClear.CanFocus = true;
		this.memClear.Name = "memClear";
		this.memClear.UseUnderline = true;
		this.memClear.Label = global::Mono.Unix.Catalog.GetString ("MC");
		this.hbuttonbox3.Add (this.memClear);
		global::Gtk.ButtonBox.ButtonBoxChild w12 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox3 [this.memClear]));
		w12.Expand = false;
		w12.Fill = false;
		// Container child hbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
		this.butt7 = new global::Gtk.Button ();
		this.butt7.CanFocus = true;
		this.butt7.Name = "butt7";
		this.butt7.UseUnderline = true;
		this.butt7.Label = global::Mono.Unix.Catalog.GetString ("7");
		this.hbuttonbox3.Add (this.butt7);
		global::Gtk.ButtonBox.ButtonBoxChild w13 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox3 [this.butt7]));
		w13.Position = 1;
		w13.Expand = false;
		w13.Fill = false;
		// Container child hbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
		this.butt8 = new global::Gtk.Button ();
		this.butt8.WidthRequest = 20;
		this.butt8.HeightRequest = 20;
		this.butt8.CanFocus = true;
		this.butt8.Name = "butt8";
		this.butt8.UseUnderline = true;
		this.butt8.Label = global::Mono.Unix.Catalog.GetString ("8");
		this.hbuttonbox3.Add (this.butt8);
		global::Gtk.ButtonBox.ButtonBoxChild w14 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox3 [this.butt8]));
		w14.Position = 2;
		w14.Expand = false;
		w14.Fill = false;
		// Container child hbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
		this.button11 = new global::Gtk.Button ();
		this.button11.CanFocus = true;
		this.button11.Name = "button11";
		this.button11.UseUnderline = true;
		this.button11.Label = global::Mono.Unix.Catalog.GetString ("9");
		this.hbuttonbox3.Add (this.button11);
		global::Gtk.ButtonBox.ButtonBoxChild w15 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox3 [this.button11]));
		w15.Position = 3;
		w15.Expand = false;
		w15.Fill = false;
		// Container child hbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
		this.button12 = new global::Gtk.Button ();
		this.button12.CanFocus = true;
		this.button12.Name = "button12";
		this.button12.UseUnderline = true;
		this.button12.Label = global::Mono.Unix.Catalog.GetString ("/");
		this.hbuttonbox3.Add (this.button12);
		global::Gtk.ButtonBox.ButtonBoxChild w16 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox3 [this.button12]));
		w16.Position = 4;
		w16.Expand = false;
		w16.Fill = false;
		// Container child hbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
		this.button38 = new global::Gtk.Button ();
		this.button38.CanFocus = true;
		this.button38.Name = "button38";
		this.button38.UseUnderline = true;
		this.button38.Label = global::Mono.Unix.Catalog.GetString ("sqrt");
		this.hbuttonbox3.Add (this.button38);
		global::Gtk.ButtonBox.ButtonBoxChild w17 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox3 [this.button38]));
		w17.Position = 5;
		w17.Expand = false;
		w17.Fill = false;
		this.vbox4.Add (this.hbuttonbox3);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbuttonbox3]));
		w18.Position = 0;
		w18.Expand = false;
		w18.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbuttonbox4 = new global::Gtk.HButtonBox ();
		this.hbuttonbox4.Name = "hbuttonbox4";
		this.hbuttonbox4.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
		// Container child hbuttonbox4.Gtk.ButtonBox+ButtonBoxChild
		this.memRead = new global::Gtk.Button ();
		this.memRead.CanFocus = true;
		this.memRead.Name = "memRead";
		this.memRead.UseUnderline = true;
		this.memRead.Label = global::Mono.Unix.Catalog.GetString ("MR");
		this.hbuttonbox4.Add (this.memRead);
		global::Gtk.ButtonBox.ButtonBoxChild w19 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox4 [this.memRead]));
		w19.Expand = false;
		w19.Fill = false;
		// Container child hbuttonbox4.Gtk.ButtonBox+ButtonBoxChild
		this.button14 = new global::Gtk.Button ();
		this.button14.CanFocus = true;
		this.button14.Name = "button14";
		this.button14.UseUnderline = true;
		this.button14.Label = global::Mono.Unix.Catalog.GetString ("4");
		this.hbuttonbox4.Add (this.button14);
		global::Gtk.ButtonBox.ButtonBoxChild w20 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox4 [this.button14]));
		w20.Position = 1;
		w20.Expand = false;
		w20.Fill = false;
		// Container child hbuttonbox4.Gtk.ButtonBox+ButtonBoxChild
		this.button15 = new global::Gtk.Button ();
		this.button15.CanFocus = true;
		this.button15.Name = "button15";
		this.button15.UseUnderline = true;
		this.button15.Label = global::Mono.Unix.Catalog.GetString ("5");
		this.hbuttonbox4.Add (this.button15);
		global::Gtk.ButtonBox.ButtonBoxChild w21 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox4 [this.button15]));
		w21.Position = 2;
		w21.Expand = false;
		w21.Fill = false;
		// Container child hbuttonbox4.Gtk.ButtonBox+ButtonBoxChild
		this.button16 = new global::Gtk.Button ();
		this.button16.CanFocus = true;
		this.button16.Name = "button16";
		this.button16.UseUnderline = true;
		this.button16.Label = global::Mono.Unix.Catalog.GetString ("6");
		this.hbuttonbox4.Add (this.button16);
		global::Gtk.ButtonBox.ButtonBoxChild w22 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox4 [this.button16]));
		w22.Position = 3;
		w22.Expand = false;
		w22.Fill = false;
		// Container child hbuttonbox4.Gtk.ButtonBox+ButtonBoxChild
		this.button17 = new global::Gtk.Button ();
		this.button17.CanFocus = true;
		this.button17.Name = "button17";
		this.button17.UseUnderline = true;
		this.button17.Label = global::Mono.Unix.Catalog.GetString ("*");
		this.hbuttonbox4.Add (this.button17);
		global::Gtk.ButtonBox.ButtonBoxChild w23 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox4 [this.button17]));
		w23.Position = 4;
		w23.Expand = false;
		w23.Fill = false;
		// Container child hbuttonbox4.Gtk.ButtonBox+ButtonBoxChild
		this.button40 = new global::Gtk.Button ();
		this.button40.CanFocus = true;
		this.button40.Name = "button40";
		this.button40.UseUnderline = true;
		this.button40.Label = global::Mono.Unix.Catalog.GetString ("%");
		this.hbuttonbox4.Add (this.button40);
		global::Gtk.ButtonBox.ButtonBoxChild w24 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox4 [this.button40]));
		w24.Position = 5;
		w24.Expand = false;
		w24.Fill = false;
		this.vbox4.Add (this.hbuttonbox4);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbuttonbox4]));
		w25.Position = 1;
		w25.Expand = false;
		w25.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbuttonbox5 = new global::Gtk.HButtonBox ();
		this.hbuttonbox5.Name = "hbuttonbox5";
		this.hbuttonbox5.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
		// Container child hbuttonbox5.Gtk.ButtonBox+ButtonBoxChild
		this.memSet = new global::Gtk.Button ();
		this.memSet.CanFocus = true;
		this.memSet.Name = "memSet";
		this.memSet.UseUnderline = true;
		this.memSet.Label = global::Mono.Unix.Catalog.GetString ("MS");
		this.hbuttonbox5.Add (this.memSet);
		global::Gtk.ButtonBox.ButtonBoxChild w26 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox5 [this.memSet]));
		w26.Expand = false;
		w26.Fill = false;
		// Container child hbuttonbox5.Gtk.ButtonBox+ButtonBoxChild
		this.button19 = new global::Gtk.Button ();
		this.button19.CanFocus = true;
		this.button19.Name = "button19";
		this.button19.UseUnderline = true;
		this.button19.Label = global::Mono.Unix.Catalog.GetString ("1");
		this.hbuttonbox5.Add (this.button19);
		global::Gtk.ButtonBox.ButtonBoxChild w27 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox5 [this.button19]));
		w27.Position = 1;
		w27.Expand = false;
		w27.Fill = false;
		// Container child hbuttonbox5.Gtk.ButtonBox+ButtonBoxChild
		this.button20 = new global::Gtk.Button ();
		this.button20.CanFocus = true;
		this.button20.Name = "button20";
		this.button20.UseUnderline = true;
		this.button20.Label = global::Mono.Unix.Catalog.GetString ("2");
		this.hbuttonbox5.Add (this.button20);
		global::Gtk.ButtonBox.ButtonBoxChild w28 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox5 [this.button20]));
		w28.Position = 2;
		w28.Expand = false;
		w28.Fill = false;
		// Container child hbuttonbox5.Gtk.ButtonBox+ButtonBoxChild
		this.button21 = new global::Gtk.Button ();
		this.button21.CanFocus = true;
		this.button21.Name = "button21";
		this.button21.UseUnderline = true;
		this.button21.Label = global::Mono.Unix.Catalog.GetString ("3");
		this.hbuttonbox5.Add (this.button21);
		global::Gtk.ButtonBox.ButtonBoxChild w29 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox5 [this.button21]));
		w29.Position = 3;
		w29.Expand = false;
		w29.Fill = false;
		// Container child hbuttonbox5.Gtk.ButtonBox+ButtonBoxChild
		this.button22 = new global::Gtk.Button ();
		this.button22.CanFocus = true;
		this.button22.Name = "button22";
		this.button22.UseUnderline = true;
		this.button22.Label = global::Mono.Unix.Catalog.GetString ("-");
		this.hbuttonbox5.Add (this.button22);
		global::Gtk.ButtonBox.ButtonBoxChild w30 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox5 [this.button22]));
		w30.Position = 4;
		w30.Expand = false;
		w30.Fill = false;
		// Container child hbuttonbox5.Gtk.ButtonBox+ButtonBoxChild
		this.button41 = new global::Gtk.Button ();
		this.button41.CanFocus = true;
		this.button41.Name = "button41";
		this.button41.UseUnderline = true;
		this.button41.Label = global::Mono.Unix.Catalog.GetString ("1/x");
		this.hbuttonbox5.Add (this.button41);
		global::Gtk.ButtonBox.ButtonBoxChild w31 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox5 [this.button41]));
		w31.Position = 5;
		w31.Expand = false;
		w31.Fill = false;
		this.vbox4.Add (this.hbuttonbox5);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbuttonbox5]));
		w32.Position = 2;
		w32.Expand = false;
		w32.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbuttonbox6 = new global::Gtk.HButtonBox ();
		this.hbuttonbox6.Name = "hbuttonbox6";
		this.hbuttonbox6.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
		// Container child hbuttonbox6.Gtk.ButtonBox+ButtonBoxChild
		this.memAdd = new global::Gtk.Button ();
		this.memAdd.CanFocus = true;
		this.memAdd.Name = "memAdd";
		this.memAdd.UseUnderline = true;
		this.memAdd.Label = global::Mono.Unix.Catalog.GetString ("M+");
		this.hbuttonbox6.Add (this.memAdd);
		global::Gtk.ButtonBox.ButtonBoxChild w33 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox6 [this.memAdd]));
		w33.Expand = false;
		w33.Fill = false;
		// Container child hbuttonbox6.Gtk.ButtonBox+ButtonBoxChild
		this.button24 = new global::Gtk.Button ();
		this.button24.CanFocus = true;
		this.button24.Name = "button24";
		this.button24.UseUnderline = true;
		this.button24.Label = global::Mono.Unix.Catalog.GetString ("0");
		this.hbuttonbox6.Add (this.button24);
		global::Gtk.ButtonBox.ButtonBoxChild w34 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox6 [this.button24]));
		w34.Position = 1;
		w34.Expand = false;
		w34.Fill = false;
		// Container child hbuttonbox6.Gtk.ButtonBox+ButtonBoxChild
		this.button25 = new global::Gtk.Button ();
		this.button25.CanFocus = true;
		this.button25.Name = "button25";
		this.button25.UseUnderline = true;
		this.button25.Label = global::Mono.Unix.Catalog.GetString ("+/-");
		this.hbuttonbox6.Add (this.button25);
		global::Gtk.ButtonBox.ButtonBoxChild w35 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox6 [this.button25]));
		w35.Position = 2;
		w35.Expand = false;
		w35.Fill = false;
		// Container child hbuttonbox6.Gtk.ButtonBox+ButtonBoxChild
		this.button26 = new global::Gtk.Button ();
		this.button26.CanFocus = true;
		this.button26.Name = "button26";
		this.button26.UseUnderline = true;
		this.button26.Label = global::Mono.Unix.Catalog.GetString (".");
		this.hbuttonbox6.Add (this.button26);
		global::Gtk.ButtonBox.ButtonBoxChild w36 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox6 [this.button26]));
		w36.Position = 3;
		w36.Expand = false;
		w36.Fill = false;
		// Container child hbuttonbox6.Gtk.ButtonBox+ButtonBoxChild
		this.button27 = new global::Gtk.Button ();
		this.button27.CanFocus = true;
		this.button27.Name = "button27";
		this.button27.UseUnderline = true;
		this.button27.Label = global::Mono.Unix.Catalog.GetString ("+");
		this.hbuttonbox6.Add (this.button27);
		global::Gtk.ButtonBox.ButtonBoxChild w37 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox6 [this.button27]));
		w37.Position = 4;
		w37.Expand = false;
		w37.Fill = false;
		// Container child hbuttonbox6.Gtk.ButtonBox+ButtonBoxChild
		this.button42 = new global::Gtk.Button ();
		this.button42.CanFocus = true;
		this.button42.Name = "button42";
		this.button42.UseUnderline = true;
		this.button42.Label = global::Mono.Unix.Catalog.GetString ("=");
		this.hbuttonbox6.Add (this.button42);
		global::Gtk.ButtonBox.ButtonBoxChild w38 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox6 [this.button42]));
		w38.Position = 5;
		w38.Expand = false;
		w38.Fill = false;
		this.vbox4.Add (this.hbuttonbox6);
		global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbuttonbox6]));
		w39.Position = 3;
		w39.Expand = false;
		w39.Fill = false;
		this.vbox3.Add (this.vbox4);
		global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.vbox4]));
		w40.Position = 1;
		w40.Expand = false;
		w40.Fill = false;
		this.vbox1.Add (this.vbox3);
		global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox3]));
		w41.Position = 2;
		w41.Expand = false;
		w41.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 510;
		this.DefaultHeight = 269;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.backspace.Clicked += new global::System.EventHandler (this.OnBackspaceClicked);
		this.clearField.Clicked += new global::System.EventHandler (this.OnClearFieldClicked);
		this.C.Clicked += new global::System.EventHandler (this.OnCClicked);
		this.memClear.Clicked += new global::System.EventHandler (this.OnMemClearClicked);
		this.butt7.Clicked += new global::System.EventHandler (this.OnNumberClicked);
		this.butt8.Clicked += new global::System.EventHandler (this.OnNumberClicked);
		this.button11.Clicked += new global::System.EventHandler (this.OnNumberClicked);
		this.button12.Clicked += new global::System.EventHandler (this.OnOperationClicked);
		this.button38.Clicked += new global::System.EventHandler (this.OnButton38Clicked);
		this.memRead.Clicked += new global::System.EventHandler (this.OnMemReadClicked);
		this.button14.Clicked += new global::System.EventHandler (this.OnNumberClicked);
		this.button15.Clicked += new global::System.EventHandler (this.OnNumberClicked);
		this.button16.Clicked += new global::System.EventHandler (this.OnNumberClicked);
		this.button17.Clicked += new global::System.EventHandler (this.OnOperationClicked);
		this.button40.Clicked += new global::System.EventHandler (this.OnOperationClicked);
		this.memSet.Clicked += new global::System.EventHandler (this.OnMemSetClicked);
		this.button19.Clicked += new global::System.EventHandler (this.OnNumberClicked);
		this.button20.Clicked += new global::System.EventHandler (this.OnNumberClicked);
		this.button21.Clicked += new global::System.EventHandler (this.OnNumberClicked);
		this.button22.Clicked += new global::System.EventHandler (this.OnOperationClicked);
		this.button41.Clicked += new global::System.EventHandler (this.OnButton41Clicked);
		this.memAdd.Clicked += new global::System.EventHandler (this.OnMemAddClicked);
		this.button24.Clicked += new global::System.EventHandler (this.OnNumberClicked);
		this.button25.Clicked += new global::System.EventHandler (this.OnButton25Clicked);
		this.button26.Clicked += new global::System.EventHandler (this.OnNumberClicked);
		this.button27.Clicked += new global::System.EventHandler (this.OnOperationClicked);
		this.button42.Clicked += new global::System.EventHandler (this.OnOperationClicked);
	}
}
